nuxt-community/sentry-module

README.md
lib/sentry.js
lib/templates/sentry-client.js

This PR adds more options to the module and providing easier config methods.

feat: more options

---

lib/templates/sentry-client.js

We could do something like:
```js
import {User} from './api'
export default {
// ..
methods: {
async fetchUsers() {
try () {
this.users = await User.fetchAll()
} catch (err) {
this.$raven.captureException(err)
}
}
}
}
```

Inject Raven to the context as $raven

---

lib/sentry.js

Fixes #17 
Based on @DiederikvandenB's solution

Add option.dsn check

---

lib/sentry.js
package.json

use debug module like other nuxt packages

---

.eslintignore
README.md
lib/module.js
lib/sentry.client.js
lib/sentry.server.js
package.json
yarn.lock

sentry 5 update
plugin for server side
deprecate nuxt 1.0
Fixes #70 #68 #73 #63

v3 update ( sentry 5, ssr plugin )

---

lib/module.js

Do not initialize Sentry if DSN is not defned

---

lib/sentry.client.js
lib/sentry.server.js

This solves https://github.com/nuxt-community/sentry-module/issues/130.

Add sentry dollar alias to context

---

package.json
types/index.d.ts

as discussed in #67 . Thanks @rchl for the hint 
regards

feat: add typescript types for $sentry

---

lib/sentry.mocked.js

fix: don't use Proxy to avoid problems with IE11 compatibility

---

README.md
lib/module.js

feat: add sourceMapStyle option

---

README.md

`sourceMapStyle` looks string, not bool value.

fix Incorrect `sourceMapStyle` type

---

lib/module.js

fix: allow overriding webpackConfig urlPrefix

---

README.md
lib/module.js

fix: log state of the Sentry logging properly

---

.eslintignore
README.md
lib/module.js
lib/sentry.mocked.js

fix: add an option to toggle logs when calling mocked instance

---

lib/core/hooks.js

fix: crash on enabling publishRelease with no "release"

---

README.md

docs: update link to config options documentation

---

README.md
jest.config.js
lib/core/hooks.js
lib/plugin.client.js
lib/plugin.lazy.js
package.json
test/default.test.js
test/fixture/default/nuxt.config.js
test/fixture/default/pages/index.vue
test/fixture/lazy/nuxt.config.js
test/fixture/lazy/pages/index.vue
test/fixture/with-lazy-config/nuxt.config.js
test/fixture/with-lazy-config/pages/index.vue
test/fixture/with-lazy-config/pages/mounted.vue
test/lazy.test.js
test/setup.js
test/utils.js
test/with-lazy-config.test.js
tsconfig.json
yarn.lock

Also:
- switch to browser testing to be able to test client-side also
Resolves #251

fix: support overriding integrations from @sentry/browser

---

types/extend.d.ts

fix(types): add missing TS types for lazy-loading feature

---

docs/content/en/sentry/options.md
lib/core/hooks.js
lib/plugin.client.js
lib/plugin.lazy.js

fix: support configuring "CaptureConsole" and "Debug" integrations

---

docs/content/en/guide/setup.md

Include instructions for adding types

docs: Add info about using module types

---

lib/core/hooks.js

fix: handle commonjs/es import styles for @sentry/cli

---

docs/content/en/sentry/options.md

At least until options for ORG, AUTH and maybe PROJECT are available.

docs: clarified publishRelease config requirements

---

docs/content/en/sentry/options.md

docs: clarify that setCommits is not set by default

---

.eslintrc.js
.github/workflows/ci.yml
lib/core/hooks.js
lib/core/options.js
lib/module.js
lib/plugin.client.js
lib/plugin.lazy.js
package.json

The server Sentry config was not always consistent. The resolved config
might have been a bit different depending on if using nuxt dev or
nuxt start.

refactor(options): refactor options resolving

---

.eslintrc.js
lib/core/hooks.js
lib/core/options.js
lib/module.js
lib/plugin.client.js
lib/plugin.lazy.js
test/fixture/default/nuxt.config.js
test/fixture/default/pages/index.vue
test/fixture/lazy/nuxt.config.js
test/fixture/lazy/pages/index.vue
test/fixture/with-lazy-config/nuxt.config.js
test/fixture/with-lazy-config/pages/index.vue
test/fixture/with-lazy-config/pages/mounted.vue

Because it's the only sane way.

chore(lint): enable comma-dangle eslint rule

---

docs/content/en/guide/usage.md

docs: add information about enriching events

---

docs/content/en/guide/setup.md

fix(guide): use correct yarn upgrade command

---

lib/plugin.client.js

fix: apply runtime config last, after merging tracing options

---

lib/core/options.js
lib/plugin.client.js
lib/plugin.lazy.js
package.json
yarn.lock

fix: Windows paths for custom client configuration files

---

src/module.ts
src/types/configuration.d.ts
src/types/extend.d.ts
src/types/index.d.ts

fix(types): fix "any" type in arguments of config.beforeSend

---

src/kit-shim.ts

fix: crash happening when `@nuxt/kit` is installed

---

package.json
src/kit-shim.ts
src/options.ts
test/options.test.ts

There was an issue with tracing options not being resolved properly on the server.
Refactored options resolving to make it less brittle and added tests.
Fixes #567

fix(tracing): tracing not enabled on the server

---

CHANGELOG.md
docs/content/en/configuration/options.md
docs/content/en/getting-started/setup.md
docs/content/en/guide/migration.md
docs/content/en/guide/releases.md
package.json
src/hooks.ts
src/module.ts
src/types/configuration.d.ts
test/fixture/default/nuxt.config.cjs
yarn.lock

feat!: upgrade to webpack-plugin v2 for making releases

---

docs/content/en/index.md

I also added a link to @manniL 's recipe.

docs: alert about support being limited to Nuxt 2
