nuxt-community/sentry-module

lib/sentry.js
The DNS with the private key is deprecated according the Sentry documentation https://docs.sentry.io/clients/node/config/#environment-variables.
This PR add a verification, if the private_key was informed so use it if not use the new DSN format
=> Added a fallback to deprecated DSN

lib/sentry.js
Option `disabled` with `true` value is ignored because of bug in the module.
This PR fixes it.
=> Fix checking the option 'disabled'

README.md, lib/sentry.js, lib/templates/sentry-client.js, package.json, test/fixture/nuxt.config.js, yarn.lock
Sentry now have new packages. While old one will work, there wont be any new features added, only bugfixes.
https://forum.sentry.io/t/switching-to-sentry-javascript/4732
Not tested, help with testing welcome ;)
=> feat: use new sentry sdk

lib/templates/sentry-client.js
Adds default integrations back in (such as user agent and breadcrumb info), which are unset in the new Sentry SDK when `integrations` is set explicitly. Resolves https://github.com/nuxt-community/sentry-module/issues/43. Further reference: https://github.com/getsentry/sentry-javascript/issues/1764
=> Add browser default integrations back

lib/sentry.js
Sentry for server is not initialized since the check is done on options.config.dsn. It should be done on options.dsn.
=> checking should be for options.dsn and not options.config.dsn

lib/sentry.js
'return' disappeared at this commit. So it does not work.
https://github.com/nuxt-community/sentry-module/commit/31d3db941ab79cf79d52e30d2986f0fe373a0f8b#diff-e6ee66530234110522eee8b87cee6b9f
=> Fix: disabled option does not work (#51)

README.md
The key name of option which pass to `Sentry.init` should be `config`.
=> Fixed option object name

package.json
@sentry/webpack-plugin is required as a dependency but is currently listed under devDependencies.
=> Fix: @sentry/webpack-plugin dependency

README.md, lib/sentry.js, package.json
With no top level 'sentry' object defined in nuxt-config.js, the code
would try to access property of undefined object as
this.options.sentry is undefined. Fixed by using deepmerge package which
both fixes the problem and makes code cleaner.
Also fixed problem with merging dsn property value with the object.
As dsn value is a string, don't use ... on it as that would turn string
into an array of letters.
=> fix: fix module options

lib/sentry.client.js
On the `sentry.client.js`
https://github.com/nuxt-community/sentry-module/blob/42d70b0485054d46f2bf430a4b64244f96fe8b66/lib/sentry.client.js#L19
will never be true since `initialize` is not a property of `options.config` as seen here
https://github.com/nuxt-community/sentry-module/blob/42d70b0485054d46f2bf430a4b64244f96fe8b66/lib/module.js#L86-L94
So the simplest solution, without having to modify any other parts of the codes than the line itself is to convert the if condition to a serialized template and referencing `options.initialize` instead of `opts.initialize`
```
if (<%= serialize(options.initialize) %>) {
Sentry.init(opts)
}
```
Signed-off-by: Uni Sayo <unibtc@gmail.com>
=> fix(client): client not being initialized

lib/module.js
This should fix compatibility with Nuxt >=2.10 while still being compatible with older versions.
=> Use officially supported devtool value

README.md, lib/module.js
Fixes #121 
It sets the `--auto` flag to `true`. This means that when `publishRelease` is `true`, it will by default auto discover the repo, last commit etc.
If users don't like this behaviour and they can one of two things:
1. Disable attaching commits completely by setting env`SENTRY_AUTO_ATTACH_COMMITS=false` or `attachCommits: false` in config.
2. Set the commit themselves in the `nuxt.config.js`:
```js
export default {
// ...
sentry: {
dsn: 'https://your-dsn@sentry.io/project-id',
webpackConfig: {
setCommits: {
repo: 'organisation/repo-name',
commit: 'your-commit-hash',
auto: false,
},
},
},
}
```
Before this should be merged, two PRs at Sentry should be merged first:
=> Set release to auto by default

README.md, lib/module.js
That change shouldn't have been released in minor version as it
is likely to break workflows since releasing commit often needs extra
configuration/work on the repo and/or sentry side.
For example for me it caused:
[error] Command failed: /var/lib/jenkins/jobs/workspace/node_modules/@sentry/cli/sentry-cli releases set-commits 2.22.107 --auto
error: API request failed
caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)
=> Disable commit releasing by default since it's a breaking change

lib/module.js, lib/sentry.mocked.js
as discussed in #84 this would be a way to ensure $sentry is there all the time.
=> feat: mock sentry in case it is disabled

package.json, types/index.d.ts
@sentry/types was misleading, and not the right import for the types. essential functions like withScope were not part of the implementation. I checked the sentry code, and found out there is indeed a little difference between client and server, BUT only in terms of configuration. @sentry/minimal is the function set for error logging which all implementations support. regarding error logging they seem all identical. The difference lies in configuration objects like BrowserOptions vs NodeOptions etc...
I also tested with a new sentry.io account how the events look like and how the additional data is appended. Therefore I post it here again, this is the right way to append extras or other data to ONE single event. If you do this.$sentry.setExtra() it will be added to the current global …
=> fix(types): use @sentry/minimal instead of @sentry/types

lib/module.js
With the following project structure:
```
- package.json ( nuxt build src/my-app )
- node_modules
- src
|  - my-app
|  | - nuxt.config.js (srcDir: __dirname )
```
The release did not work:
```
error: .nuxt/dist/server: IO error for operation on .nuxt/dist/server: No such file or directory (os error 2)
```
This was due to the fact that the sentry-CLI is run with working
directory being where package.json is located while the relative
path resolved by the module was relative to the app (my-app) directory.
Fix by passing absolute path to sentry-cli so that it doesn't matter
what's the working directory when it's run.
Relevant doc: https://nuxtjs.org/api/configuration-rootdir/
Fix based on original PR by @matthiusieben - https://github.com/nuxt-community/sentry-module/pull/122
Resolves #132
=> fix: release failure with non-standard directory structure

lib/module.js
While nuxt by default enables `cheap-module-source-map` source maps on
server, that doesn't seem to produce any map files in `.nuxt/dist/server/`.
I'm not sure why but in any case, we shouldn't rely on Nuxt as that's
not guaranteed anyway.
Since vue files are also compiled on server, it makes sense to enable
source maps on server also. While I couldn't see evidence of Sentry
using them directly, they do improve stack traces in Node and Sentry
benefits from that indirectly.
=> fix: enable source maps on server also

lib/module.js
Resolves https://github.com/nuxt-community/sentry-module/issues/148
=> fix: allow string type to webpackConfig.include

lib/module.js
Only source/map files uploaded for the client need the `_nuxt` prefix.
Server files don't have such prefix concept.
=> fix: don't set urlPrefix for release on server

lib/module.js
urlPrefix for map files pushed to Sentry needs to be prefixed with
router.base in case user has modified it to be something else than '/'.
Otherwise Sentry can't map paths in client-side errors to uploaded
sources and map files.
Resolves #105
=> fix: router.base not taken into account when releasing source maps

types/extend.d.ts, types/index.d.ts, types/node.d.ts
Extending a namespace must be done in a definition file that has no
top-level imports so that the file is treated as ambient module
rather than a normal module. For that reason, I couldn't just put new
code in `index.d.ts` but had to create separate file. Stuff from
`index.d.ts` moved to `extend.d.ts` to have a cleaner structure.
=> fix(types): add types for process.sentry

lib/module.js
In c71d8488c2b017dcdc2ecdb560b53fe5f4f671f4 I've broken release of
client source maps by not setting `config.devtool = 'source-map'` for
the client build. I've missed the condition that returns early on client
build.
In 8e3e4d1c8289a8abae7337bbca8362da6fc5c1b9 I've also attempted to
configure urlPrefix separately for client and server but I've missed
the fact that client and server source maps were not uploaded
separately but there was only one upload on building server (which
builds second). So the prefix that was actually used was the server
one.
Fix by going to previous logic of setting urlPrefix once (at the expense
of it being incorrect on the server). To fix that properly, we would
need to make two separate releases but that is non-trivial since
releasing can include source maps …
=> fix: released client sourcemaps don't have correct prefix (no /_nuxt/)

.eslintignore, .release-it.js, package.json, yarn.lock
Main advantage being that it:
- allows reviewing changelog before release
- creates Github release (when GITHUB_TOKEN is provided)
Kept previous release package.json script renamed to `release-legacy`.
=> chore(release): use release-it for making releases

lib/module.js
If a custom webpack config is added by another module, that other config would **not** have the `WebpackPlugin` added to its plugins since `extendBuild` is called only when NuxtJS build the initial list of `webpackConfigs`, and not on the actual list of webpack configurations. The `webpack:config` can be used to manipulate the actual list of webpack configuration that will be used, even those added by a custom module.
=> Setup WebpackPlugin during webpack:config hook

lib/module.js
Because currently upload filename looks like `\_nuxt\/001c573c077135db8d5a.js`
And I want to set `urlPrefix: "~/_nuxt/"` by myself
=> Leave possibility to fill manually `urlPrefix` field for windows users

README.md, lib/module.js
Sentry by default swallows all errors caught by Vue error handler. This
options re-posts them so that they show up in the console.
I have always had this enabled in my configuration and I think it makes sense to have it enabled by default.
=> fix: enable console logging of Vue errors in development

lib/core/hooks.js
Catch Sentry CLI better to avoid crashing when running outside of git repo.
Resolves #200
=> fix: crash on running module outside of git repo when release not set

lib/plugin.lazy.js
It looks like the code allowed "loadSentry()" to run more than once and
the first run would unset "delayedCalls" causing second run to crash on
trying to iterate it.
=> fix: crash on iterating "delayedCalls"

lib/plugin.lazy.js
This ensures that the global errors that were delayed will be reported using the same mechanism (`onerror`) as they normally would. Makes it clearer in the Sentry UI what the error is.
=> fix(lazy): improve error reporting for postponed global errors

lib/core/hooks.js, lib/module.js
Switched from "listen" to "ready" hook so that server-side Sentry is
also initialized when starting Nuxt programmatically from within a server
framework like expressjs.
The side effect of using "ready" hook is that Sentry will also be
initialized on building which seems like an OK thing to do.
Also, in a typical case, "ready" triggers before "listen" which should
actually be better as it would also catch issues with starting server
listener.
Resolves #230
=> fix: initialize server-side Sentry when using Nuxt programmatically

README.md, lib/core/hooks.js, lib/module.js, lib/plugin.client.js, package.json, types/sentry.d.ts
Based off the work of @Manfies in #196, but updated to take some of the feedback from the PR into account. 
* Added a top level `enableTracing` option, default `false`
* If enabled, can provide a sample rate value via `tracesSampleRate` property in the option.
This works for my use case, but this is my first contribution to this package so please provide any and all feedback.
=> feat: add support for performance monitoring/tracing

lib/plugin.client.js
Fixes #266 
Check config when the option is a function then using `serializeFunction(option)` instead of using `serialize(option)`
=> fix: better handling of functions options in config

lib/plugin.lazy.js, test/default.test.js, test/fixture/lazy/nuxt.config.js, test/lazy.test.js, test/with-lazy-config.test.js
Solution for https://github.com/nuxt-community/sentry-module/issues/285
The error occurs because we do a dynamic import of `lodash.merge` which is a CommonJS module.
=> fix: crash on lazy loading when using Runtime Config

docs/package.json, docs/yarn.lock
This is what currenty [Sentry docs](https://sentry.nuxtjs.org/) shows:
It turns out, on `@nuxt/content-theme-docs` `^0.10.0` and higher, the styling's broken. Reverting the version back to `^0.9.0` fixes the problem.
=> fix(docs): fixes typography & content styling

lib/templates/options.ejs
=> fix: serialize regexpes properly in the server-side config

lib/core/hooks.js
This small change allows release to be set to undefined without being overridden with automatic release.
In v4 it was possible to set `clientConfig: { release: undefined }` (and same for server) to override automatically generated value. In v5 the merging library has been changed to `lodash.merge` which is ignoring `undefined` values making it no longer possible to override automatic release generation.
We prefer not to include release in the configuration to avoid unnecessary changes to built files (small perf improvement for returning visitors). Instead we rely on `window.SENTRY_RELEASE`/`process.env.SENTRY_RELEASE`. For that to work [release must be undefined](https://github.com/getsentry/sentry-javascript/blob/7f87dd207123d0b2c56e7834f26650de24363d4a/packages/browser/src/sdk.ts#L80-L86 …
=> feat: allow disabling automatic version detection for releases

docs/content/en/guide/setup.md
It's confusing that "configuration" is both used for the native sentry options (config object), as well as for the module options. I tried to clarify this a bit in this PR.
=> docs: clarification between module and native sentry options

docs/content/en/guide/usage.md
Clarified that Sentry automatically reports all errors, and no manual commands are needed.
=> docs: clarify Sentry zero-config automatic reporting

docs/content/en/sentry/options.md, lib/core/hooks.js, lib/core/utils.js, lib/module.js, package.json, test/fixture/default/nuxt.config.js, types/sentry.d.ts, yarn.lock
Apart from allowing all webpackConfig options to be overridden, also
deprecate "webpackConfig" and other publish-release-specific options
and accept a configuration object for the "publishRelease" option.
=> fix: allow overriding all "webpackConfig" options

lib/core/hooks.js, lib/module.js, package.json
To avoid Sentry blocking the message loop and triggering a warning
that it's blocking the exit, explicitly shutdown Sentry after generating.
Fixes #352
=> fix: shutdown Sentry instance after generate

docs/content/en/sentry/lazy-loading.md
I suppose `errorListener` should be called on `this` in the following example:
```js
mounted() {
// This will only load sentry once an error was thrown
// To prevent a chicken & egg issue, make sure to also
// set injectMock: true if you use this so the error
// that triggered the load will also be captured
this.errorListener = () => {
this.$sentryLoad()
window.removeEventListener('error', errorListener)
}
window.addEventListener('error', errorListener)
},
destroyed() {
window.removeEventListener('error', this.errorListener)
}
```
=> fix(docs): typo in the lazy-loading section

lib/core/hooks.js
Some context in https://github.com/getsentry/sentry-javascript/issues/4186
which shows that passing empty object to some integrations (ExtraErrorData
for example) will make it not assume default values for some options.
=> fix: don't pass empty object to integrations constructor

docs/content/en/sentry/options.md, lib/core/hooks.js, package.json, yarn.lock
BREAKING CHANGE: To use the "publishRelease" option, it's now necessary to manually install the `@sentry/webpack-plugin` package as a dev dependency.
This is in response to Sentry change https://github.com/getsentry/sentry-webpack-plugin/pull/343 which inadvertently made webpack dependencies get installed in production.
=> fix(deps)!: make @sentry/webpack-plugin a peer dependency

docs/content/en/sentry/options.md, lib/core/hooks.js, lib/module.js, types/sentry.d.ts
BREAKING CHANGE: The removed `attachCommits` and `repo` options can be
set through the `publishRelease` object.
=> refactor(options)!: remove deprecated "attachCommits" and "repo"

docs/content/en/sentry/options.md, lib/core/hooks.js, lib/module.js, types/sentry.d.ts
BREAKING CHANGE: Configure through the publishRelease object instead.
=> refactor(options)!: remove deprecated "webpackConfig"

lib/core/hooks.js, lib/core/options.js, lib/module.js
BREAKING CHANGE: The server-side process.sentry will be created slightly later than before WHEN running the "build" action. It will be created before the pages are built (on `build:compile` hook) while before it was available a bit earlier on `ready` hook (with an issue that it was not always able to pass the project version to Sentry).
=> fix!: describe a breaking change

.github/workflows/ci.yml
Time to move on.
One issue is with `release-it` that doesn't support node 12 anymore but Nuxt also doesn't really as it expects that latest LTS version is used (16 at this time).
=> chore(ci): disable node 12 testing

lib/core/options.js, package.json, types/sentry.d.ts, yarn.lock
After recent refactorings, the client side config was missing the `tracesSampleRate` default value if `tracing` was enabled, resulting in no tracing.
Fixes #447
=> fix(tracing): set `tracesSampleRate` when `tracing` enabled

lib/core/options.js, lib/plugin.client.js, package.json, test/fixture/default/nuxt.config.js, yarn.lock
Original code did not resolve `options.tracing: true` to an object with default properties. This resulted in `Vue` integration getting those options:
```js
new Vue({ Vue: VueLib, ...{"attachProps":true,"logErrors":false}}),
```
rather than:
```js
new Vue({ Vue: VueLib, ...{"attachProps":true,"logErrors":false,"tracing":true,"tracingOptions":{"hooks":["mount","update"],"timeout":2000,"trackComponents":true}}}),
```
and likely Vue tracing not working.
=> fix(tracing): merge user's tracing configuration

lib/core/options.js
The warning is referencing to customServerIntegrations instead of customClientIntegrations.
=> fix: incorrect option name in the warning message

lib/core/hooks.js, lib/core/utils.js, lib/module.js, package.json, types/sentry.d.ts, yarn.lock
While investigating tracing functionality, I've noticed some broken/non-ideal behavior.
- Due to Sentry `requestHandler` being created from the `render:setupMiddleware` hook and Sentry being initialized from the `build:compile` hook (or `ready` in production), the tracing functionality did not get initialized properly on the server-side because request handler was created before Sentry was initialized. Sentry [request handler logic](https://github.com/getsentry/sentry-javascript/blob/7db0b7f7139bc7abd8d83d420bb3c924b08e15d1/packages/node/src/handlers.ts#L146-L164) requires that Sentry is initialized first.
Created a proxy that uses dummy handler until Sentry is initialized, at which point it gets replaced with Sentry's own handler.
- The `build:compile` and `build:before` hooks run once …
=> fix(tracing): autoSessionTracking not working on the server-side

docs/content/en/sentry/options.md, docs/content/en/sentry/runtime-config.md, lib/core/options.js
=> fix: gracefully handle Nuxt versions without Runtime Config

docs/content/en/sentry/options.md, lib/plugin.client.js, lib/plugin.lazy.js, test/default.test.js, test/fixture/default/pages/index.vue, test/fixture/lazy/nuxt.config.js
Enables Vue Router instrumentation by default when `tracing` is enabled and fixes a crash with `lazy`+`tracing`.
Depends on https://github.com/wix/sentry-testkit/pull/152 for the new test to start passing.
EDIT: Will re-introduce new tests after sentry-testkit is fixed.
=> feat(tracing): enable Vue Router instrumentation by default

docs/content/en/sentry/options.md, lib/core/options.js, lib/plugin.client.js, lib/plugin.lazy.js, types/sentry.d.ts
Adds support for passing a path to a plugin (file that exports a function) for `clientConfig` and `serverConfig` options. Allows to configure options that would otherwise be impossible to handle due to serialization of options that Nuxt requires.
Resolves #385
Resolves #410
Resolves #343
Resolves #226
=> feat: support plugin path for clientConfig and serverConfig

lib/core/hooks.js, package.json
This shaves off about 22KB of parsed (about 3KB gzipped) code.
=> feat: enable tree shaking of Sentry SDK debug code

docs/content/en/sentry/options.md, lib/core/options.js
Add support for [HttpClient](https://docs.sentry.io/platforms/javascript/configuration/integrations/plugin/#httpclient) client integration
Resolves #503
=> feat: support HttpClient client integration

docs/content/en/sentry/options.md, lib/core/options.js, lib/plugin.client.js, lib/plugin.lazy.js
Some integrations were missing from the list so it was not possible to configure or enable those.
=> fix: update list of allowed integrations and allow configuring them

lib/core/hooks.js, lib/core/options.js
The `@sentry/tracing` package has to be imported so that some tracing extensions are added.
Also forgot to pass `tracing` option on the server so tracing was never enabled there.
Fixes #508
=> fix(tracing): initialize server side tracing correctly

package.json, src/module.ts, src/templates/plugin.server.js, test/default.test.ts, test/fixture/default/pages/index.vue, test/fixture/lazy/pages/index.vue, test/fixture/with-lazy-config/pages/index.vue, test/lazy.test.ts, test/with-lazy-config.test.ts, yarn.lock
=> fix(tracing): connect backend and frontend traces

src/hooks.ts, src/options.ts, src/templates/plugin.client.js, test/fixture/lazy/nuxt.config.cjs
The `import * as Sentry from '~@sentry/vue'` has prevented tree shaking from working.
This results in about 221KB reduction when using `tracing` and a bit less when not using `tracing` (that's weird, yes, but looks like related to Sentry SDK itself).
Unfortunately it doesn't benefit when using `lazy` loading. Maybe there is a way to handle it using webpack's magic comments in https://github.com/nuxt-community/sentry-module/blob/994f333a8dfbc8cb4ecefbbc8042752d804b7f64/src/templates/plugin.lazy.js#L112-L112 but I haven't investigated at that point.
EDIT: There is a webpack magic comment [`webpackExports`](https://webpack.js.org/api/module-methods/) but it's only available from webpack 5.
=> fix: significantly reduce client bundle size

src/hooks.ts, src/module.ts, src/options.ts, src/templates/client.shared.js, src/templates/plugin.client.js, src/templates/plugin.lazy.js, tsconfig.json
The `import * as Sentry from '~@sentry/vue'` has prevented tree shaking from working.
Second attempt. This time also handling `lazy` and exposing all relevant SDK methods on `$sentry`.
Gzipped savings for the whole client bundle for this module's test fixture:
- Non-lazy: 208kb -> 140kb
- Lazy: 430kb -> 340kb
Also greatly reduces duplicated code in lazy and non-lazy plugins, simplifying maintenance. The code of those two was already slightly out of sync.
=> chore: publish to npm on release

src/module.ts
In some monorepo setups the aliases were resolved to root dependencies which might not have been the right ones.
Fixes #546
=> fix: resolve aliases relative to module's dir

.github/workflows/ci.yml, src/hooks.ts, src/module.ts
Don't shutdown Sentry SDK after build in dev mode and also expose Sentry SDK on the server on the `process.sentry` regardless if initializing SDK or not. This is how it worked before and was changed later for reasons that were later reversed anyway so this change should be reversed too.
=> fix: don't shutdown Sentry SDK after build in dev mode

docs/content/en/configuration/options.md, src/module.ts
I'm not sure why we even enable `ReportingObserver` integration by default since it seems to produce a lot of reports that are not really that useful. But instead of removing it completely, only include the `crash` report types (so exclude `deprecation` and `intervention` by default) to keep those reports to minimum.
=> fix: only include 'crash' type for `ReportingObserver` integration

docs/content/en/guide/session-replay.md
Updated documentation to use `Replay` as the client integration key, not `Reply`
=> chore(docs): update typos in Session Replay page

src/kit-shim.ts
=> fix: ensure Sentry re-initializes in Dev after Nuxt config change

build.config.ts, package.json, src/kit-shim.ts, yarn.lock
I suppose I could have fixed it by using different context name than `nuxt` but there is not really any need for this package since the context is not even used outside of a single file.
Fixes #557
=> fix: remove use of unctx to avoid issues with conflicting versions

src/options.ts
With `defu` the leftmost arguments have priority. The code did merging backwards due to it using a different library that had opposite logic.
Fixes #567
=> fix: config merging order on the server side

docs/content/en/configuration/options.md, src/options.ts, src/templates/client.shared.js, src/types/configuration.d.ts, test/options.test.ts
Allows setting `tracing.vueRouterInstrumentationOptions` to specify options passed to `vueRouterInstrumentation` integration.
Resolves #613
=> feat(tracing): allow configuring vueRouterInstrumentation options

src/templates/plugin.lazy.js
I've noticed that this code can crash on checking `'reason' in event.detail` because `in` check crashes when the right-hand side is `undefined`.
See also the corresponding Sentry SDK issue: https://github.com/getsentry/sentry-javascript/issues/9579
=> fix: crash on handling unhandled exceptions

docs/content/en/configuration/options.md, src/module.ts, test/fixture/typescript/api/index.ts, test/fixture/typescript/config/custom-client-integrations.ts, test/fixture/typescript/nuxt.config.ts, test/fixture/typescript/pages/index.vue, test/options.test.ts, test/typescript.test.ts
After manually inspecting some crashes I've realized that the `RewriteFrames` integration that the module enables by default does more harm than good.
In case there are source maps it doesn't really make any difference since stack frame paths are resolved from source maps then.
In case there are no source maps (for example when crash is within the server code and not inside the webpack context) then what `RewriteFrames` does is it [strips the whole path leaving just the file name](https://github.com/getsentry/sentry-javascript/blob/45692f4e80c49bf8aca77695e12313ee24ca8bae/packages/integrations/src/rewriteframes.ts#L83-L83). That can result in just `index.js` being shown, for example, which makes it unclear which file is being referred to.
To fix that, set `root` option on the server so …
=> fix: set `root` for RewriteFrames integration

.eslintrc.cjs, src/options.ts, src/templates/client.shared.js, test/default.test.ts, test/fixture/typescript/nuxt.config.ts, test/fixture/typescript/pages/disabled-integrations.vue, test/lazy.test.ts, test/options.test.ts, test/typescript.test.ts, test/utils.ts, test/with-lazy-config.test.ts
It wasn't possible to disable internal SDK integrations that SDK enables by default (for example `Modules` on the server and `Dedupe` on the client).
=> fix: make it possible to disable internal SDK integrations
